stateful_browser.py: Remove unusable *args from submit_selected()
It was passed to submit(), which does not accept it:

>>> import mechanicalsoup
>>> browser = mechanicalsoup.StatefulBrowser()
>>> browser.open_fake_page("<form>")
>>> browser.select_form()
<mechanicalsoup.form.Form object at 0x11107c040>
>>> browser.submit_selected(None, True, None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/mechanicalsoup/stateful_browser.py", line 247, in submit_selected
    resp = self.submit(self.__state.form, url=self.__state.url,
TypeError: submit() got multiple values for argument 'url'
>>>